### ISSUE TITLE
tinkogroupsの更新をしやすくしたい

### ISSUE THREAD

**Issue by kaminchu** [Cuderia1917/tnkgroup#1]
https://tinko.org/tinkogroups.html  
を例えばgithubpagesから取得できるようにして、プルリク更新にしたい！
（github依存になるけど・・・）

置く場所はもちろんこのプロジェクトっ

**Comment by Cuderia1917** [comment]
私依存だとそのうちやらかして飛ばしそうなので，そうした方が安全ですね．
そうしましょう（訳: そのうちします）

*実装までOpenにしておきます

**Comment by Cuderia1917** [comment]
こんな感じでどうですか
